name: Create ZIP Release

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      
      - name: Set ZIP filename
        id: branch
        run: |
            echo PROJECT_NAME=${GITHUB_REPOSITORY#*/} >> ${GITHUB_OUTPUT}
            echo ZIP_FILE=${GITHUB_REPOSITORY#*/}_${GITHUB_REF#refs/tags/}.zip >> ${GITHUB_OUTPUT}

      - name: Composer Install
        run: composer install --no-dev --ignore-platform-reqs
        
      - name: Make Zip ${{ steps.branch.outputs.ZIP_FILE }}
        run: |
          cd ..
          zip -r ${{ steps.branch.outputs.ZIP_FILE }} ${{ steps.branch.outputs.PROJECT_NAME }} -x '*/.git/*'

      - name: Upload Asset
        uses: ncipollo/release-action@v1
        with:
            artifacts: ../${{ steps.branch.outputs.ZIP_FILE }}
            token: ${{ secrets.GITHUB_TOKEN }}
            artifactErrorsFailBuild: true
            allowUpdates: true
            omitBodyDuringUpdate: true
            omitNameDuringUpdate: true
            omitPrereleaseDuringUpdate: true
